<script lang="ts">
  import { financeData } from "$lib/finance-store";
  import { currency } from "$lib/demo";
  const assets = $derived($financeData.accounts.filter((account) => account.type !== "liability"));
  const liabilities = $derived($financeData.accounts.filter((account) => account.type === "liability"));
  const assetsCop = $derived(assets.filter((item) => item.currency === "COP").reduce((sum, item) => sum + item.currentBalance, 0));
  const liabilitiesCop = $derived(liabilities.filter((item) => item.currency === "COP").reduce((sum, item) => sum + Math.abs(item.currentBalance), 0));
  const investments = $derived($financeData.pockets.filter((pocket) => ["investment", "real estate", "real_estate"].includes(pocket.purpose)));
</script>

<div class="page">
  <header class="page-header"><div><span class="eyebrow">Activos menos pasivos</span><h1>Patrimonio</h1><p>Una vista consolidada sin mezclar monedas ni inventar valoraciones.</p></div><a class="secondary-link" href="/accounts">Administrar cuentas</a></header>
  <section class="metric-grid"><article class="metric-card"><span>Activos COP</span><strong>{currency(assetsCop)}</strong><small>{assets.length} cuentas</small></article><article class="metric-card"><span>Pasivos COP</span><strong>{currency(liabilitiesCop)}</strong><small>{liabilities.length} obligaciones</small></article><article class="metric-card accent"><span>Patrimonio neto COP</span><strong>{currency(assetsCop - liabilitiesCop)}</strong><small>Actualizado desde Firefly</small></article></section>
  <section class="two-columns"><article class="panel"><header class="section-heading"><div><span class="eyebrow">Firefly III</span><h2>Activos</h2></div></header><div class="account-list">{#each assets as account}<div class="account-row"><span class="account-icon">◇</span><span><strong>{account.name}</strong><small>{account.scope === "private" ? "Solo yo" : "Compartido"} · {account.currency}</small></span><strong>{currency(account.currentBalance, account.currency)}</strong></div>{/each}{#if assets.length === 0}<div class="empty-state"><strong>Aún no hay activos</strong><p>Crea una cuenta para empezar el mapa patrimonial.</p></div>{/if}</div></article><article class="panel"><header class="section-heading"><div><span class="eyebrow">Obligaciones</span><h2>Pasivos</h2></div></header><div class="account-list">{#each liabilities as account}<div class="account-row"><span class="account-icon">↘</span><span><strong>{account.name}</strong><small>{account.currency}</small></span><strong>{currency(account.currentBalance, account.currency)}</strong></div>{/each}{#if liabilities.length === 0}<div class="empty-state"><strong>Sin pasivos registrados</strong><p>Agrega tarjetas o deudas para calcular el patrimonio real.</p></div>{/if}</div></article></section>
  <section class="section-block"><header class="section-heading"><div><span class="eyebrow">Planificación PostgreSQL</span><h2>CDTs, inversión e inmuebles</h2></div><a href="/future">Abrir simuladores</a></header>{#if investments.length}<div class="pocket-grid">{#each investments as pocket}<article class="panel"><h3>{pocket.name}</h3><p>{currency(pocket.currentAmount, pocket.currency)} reservados · meta {currency(pocket.targetAmount, pocket.currency)}</p></article>{/each}</div>{:else}<div class="empty-state panel"><strong>No hay proyectos patrimoniales todavía</strong><p>Crea bolsillos de inversión o inmueble y conserva sus supuestos en el plan futuro.</p><a class="secondary-link" href="/pockets">Crear proyecto</a></div>{/if}</section>
</div>
