import type { PocketView, TransactionView } from "./types";

export const pockets: PocketView[] = [
  {
    id: "daily",
    name: "Vida diaria",
    purpose: "Mercado · transporte · hogar",
    observations: "Mercado · transporte · hogar",
    visibility: "household",
    currency: "COP",
    currentAmount: 2_480_000,
    targetAmount: 4_000_000,
    color: "mint",
    note: "Quedan 12 días · $126.667 por día",
    policyKind: "periodic_spend",
  },
  {
    id: "home",
    name: "Cuota inicial",
    purpose: "Nuestro apartamento",
    observations: "Nuestro apartamento",
    visibility: "household",
    currency: "COP",
    currentAmount: 38_600_000,
    targetAmount: 80_000_000,
    color: "blue",
    note: "Al ritmo actual: abril de 2028",
    policyKind: "target_by_contribution",
    monthlyContribution: 1_800_000,
  },
  {
    id: "trip",
    name: "Viaje",
    purpose: "Vacaciones de fin de año",
    observations: "Vacaciones de fin de año",
    visibility: "household",
    currency: "USD",
    currentAmount: 1_850,
    targetAmount: 3_000,
    color: "sand",
    note: "Aporta US$192 al mes para llegar",
    policyKind: "target_by_date",
    targetDate: "2026-12-15",
  },
  {
    id: "private",
    name: "Mi sorpresa",
    purpose: "Solo tú puedes ver este bolsillo",
    observations: "Solo tú puedes ver este bolsillo",
    visibility: "private",
    currency: "COP",
    currentAmount: 740_000,
    targetAmount: 1_200_000,
    color: "rose",
    note: "38 % pendiente",
    policyKind: "target_by_contribution",
    monthlyContribution: 120_000,
  },
];

export const transactions: TransactionView[] = [
  {
    id: "1",
    merchant: "Éxito",
    category: "Mercado",
    pocket: "Vida diaria",
    payer: "Tú",
    amount: 186_400,
    date: "Hoy",
    occurredAt: "2026-07-19T15:30:00.000Z",
    pocketId: "daily",
    currency: "COP",
    kind: "expense",
  },
  {
    id: "2",
    merchant: "TransMilenio",
    category: "Transporte",
    pocket: "Vida diaria",
    payer: "Pareja",
    amount: 18_000,
    date: "Hoy",
    occurredAt: "2026-07-19T12:00:00.000Z",
    pocketId: "daily",
    currency: "COP",
    kind: "expense",
  },
  {
    id: "3",
    merchant: "Aporte automático",
    category: "Ahorro",
    pocket: "Cuota inicial",
    payer: "Hogar",
    amount: 900_000,
    date: "Ayer",
    occurredAt: "2026-07-18T14:00:00.000Z",
    pocketId: "home",
    currency: "COP",
    kind: "allocation",
  },
  {
    id: "4",
    merchant: "Café Quindío",
    category: "Cafés",
    pocket: "Vida diaria",
    payer: "Tú",
    amount: 22_500,
    date: "Ayer",
    occurredAt: "2026-07-18T10:00:00.000Z",
    pocketId: "daily",
    currency: "COP",
    kind: "expense",
  },
];

export const currency = (value: number, code = "COP") =>
  new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: code,
    maximumFractionDigits: code === "COP" ? 0 : 2,
  }).format(value);
